{{- if or (eq .Values.global.resourceScope "all") (eq .Values.global.resourceScope "cluster") }}
{{- if or (not .Values.istiodRemote.enabled) (and .Values.istiodRemote.enabled (or .Values.global.configCluster .Values.istiodRemote.enabledLocalInjectorIstiod)) }}
{{- $saName := printf "istiod%s" (ternary (printf "-%s" .Values.revision) "" (not (eq .Values.revision ""))) }}
{{- range $ns := (default (list) (.Values.qubership).secretsNamespaces | uniq) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istiod-secrets-reader{{- if not (eq $.Values.revision "") }}-{{ $.Values.revision }}{{- end }}-{{ $.Release.Namespace }}
  namespace: {{ $ns }}
  labels:
    app: istiod
    release: {{ $.Release.Name }}
    app.kubernetes.io/name: "istiod"
    {{- include "istio.labels" $ | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istiod-secrets-reader{{- if not (eq $.Values.revision "") }}-{{ $.Values.revision }}{{- end }}-{{ $.Release.Namespace }}
  namespace: {{ $ns }}
  labels:
    app: istiod
    release: {{ $.Release.Name }}
    app.kubernetes.io/name: "istiod"
    {{- include "istio.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: istiod-secrets-reader{{- if not (eq $.Values.revision "") }}-{{ $.Values.revision }}{{- end }}-{{ $.Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $saName }}
    namespace: {{ $.Values.global.istioNamespace }}
---
{{- end }}
{{- end }}
{{- end }}
