{
 "title": "Istio Ztunnel Dashboard",
 "description": "Istio Ztunnel Dashboard version 1.29.2",
 "tags": [ "istio" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ztunnel Versions",
   "type": "timeseries",
   "description": "Version number of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (tag) (istio_build{cluster=~\"$cluster\", component=\"ztunnel\"})",
     "legendFormat": "Version ({{tag}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{cluster=~\"$cluster\", container=\"istio-proxy\",pod=~\"ztunnel-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "alias": "limit",
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", container=\"istio-proxy\",pod=~\"ztunnel-.*\",resource=\"memory\"}",
     "legendFormat": "Memory Limit ({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", container=\"istio-proxy\",pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "alias": "limit",
     "expr": "kube_pod_container_resource_limits{cluster=~\"$cluster\", container=\"istio-proxy\",pod=~\"ztunnel-.*\",resource=\"cpu\"}",
     "legendFormat": "CPU Limit ({{pod}})"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Connections opened and closed per instance",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_tcp_connections_opened_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Opened ({{pod}})"
    },
    {
     "expr": "-sum by (pod) (rate(istio_tcp_connections_closed_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Closed ({{pod}})"
    }
   ]
  },
  {
   "title": "Bytes Transmitted",
   "type": "timeseries",
   "description": "Bytes sent and received per instance",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_tcp_sent_bytes_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Sent ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(istio_tcp_received_bytes_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Received ({{pod}})"
    }
   ]
  },
  {
   "title": "DNS Request",
   "type": "timeseries",
   "description": "DNS queries received per instance",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_dns_requests_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "Request ({{pod}})"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "XDS Connections",
   "type": "timeseries",
   "description": "Count of XDS connection terminations.\nThis will typically spike every 30min for each instance.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(istio_xds_connection_terminations_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "XDS Connection Terminations ({{pod}})"
    }
   ]
  },
  {
   "title": "XDS Pushes",
   "type": "timeseries",
   "description": "Rate of XDS messages exchanged with the control plane, by message type",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (url) (irate(istio_xds_message_total{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"}[$__rate_interval]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Workload Manager",
   "type": "timeseries",
   "description": "Count of active and pending proxies managed by each instance.\nPending is expected to converge to zero.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (workload_manager_active_proxy_count{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"})",
     "legendFormat": "Active Proxies ({{pod}})"
    },
    {
     "expr": "sum by (pod) (workload_manager_pending_proxy_count{cluster=~\"$cluster\", pod=~\"ztunnel-.*\"})",
     "legendFormat": "Pending Proxies ({{pod}})"
    }
   ]
  }
 ]
}