{{- if .Values.MONITORING_ENABLED }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ztunnel-monitor
spec:
  podMetricsEndpoints:
    - interval: {{ .Values.monitoring.scrapeInterval }}
      path: /metrics
      port: ztunnel-stats
  selector:
    matchLabels:
      app: ztunnel
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-cni-node-monitor
spec:
  podMetricsEndpoints:
    - interval: {{ .Values.monitoring.scrapeInterval }}
      path: /metrics
      port: metrics
  selector:
    matchLabels:
      k8s-app: istio-cni-node
  {{- end }}