apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ztunnel-monitor
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: ztunnel
  podMetricsEndpoints:
    - port: ztunnel-stats
      path: /metrics
      interval: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: waypoint-monitor
  namespace: core-1-core
spec:
  selector:
    matchLabels:
      gateway.istio.io/managed: istio.io-mesh-controller
  podMetricsEndpoints:
    - port: metrics
      path: /stats/prometheus
      interval: 5s